# Generated by Django 2.2.5 on 2019-11-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191118_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_class',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_subject',
            field=models.CharField(max_length=255),
        ),
    ]
