# Generated by Django 2.2.5 on 2019-11-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191118_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adrress',
            new_name='address',
        ),
    ]
