# Generated by Django 2.2.5 on 2019-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191118_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll_up',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='roll_up',
            name='id_class',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roll_up',
            name='id_subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_class',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_subject',
            field=models.CharField(max_length=255),
        ),
    ]
