# Generated by Django 2.2.5 on 2019-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191118_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_class',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
