# Generated by Django 2.2.5 on 2019-11-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191118_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_class',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(default=''),
        ),
    ]
