# Generated by Django 2.2.5 on 2019-11-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191118_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll_up',
            name='id_student',
            field=models.CharField(max_length=255),
        ),
    ]
